### ISSUE TITLE
Don't use Person.pm and other toplevel namespaces

### ISSUE THREAD

**Issue by eserte** [mishin/Ftree-cpan#2]
The "Person" namespace (for example) belongs to a different CPAN author and therefore FamilyTreeInfo is marked as "unauthorized": http://search.cpan.org/~mishin/FamilyTreeInfo-2.3.24/

Using the "Person" namespace has also other interesting side effects --- as authors often use an inline definition "Person" class in test scripts, and maybe subclass with "use base", then the presence of an installed Person.pm breaks these scripts. See https://github.com/PerlDancer/Dancer/issues/1127 and http://www.cpantesters.org/cpan/report/173920dc-5ddc-11e5-8f88-db37f321c22e where this happens.

My suggestion: put all modules used in the FamilyTreeInfo distribution under a common namespace (e.g. FamilyTreeInfo).

**Comment by mishin** [comment]
Thanks, I change it soon, today I think, sorry8:33, 23 сентября 2015 г., "Slaven Rezić" notifications@github.com:The "Person" namespace (for example) belongs to a different CPAN author and therefore FamilyTreeInfo is marked as "unauthorized": http://search.cpan.org/~mishin/FamilyTreeInfo-2.3.24/ Using the "Person" namespace has also other interesting side effects --- as authors often use an inline definition "Person" class in test scripts, and maybe subclass with "use base", then the presence of an installed Person.pm breaks these scripts. See PerlDancer/Dancer#1127 and http://www.cpantesters.org/cpan/report/173920dc-5ddc-11e5-8f88-db37f321c22e where this happens. My suggestion: put all modules used in the FamilyTreeInfo distribution under a common namespace (e.g. FamilyTreeInfo). —Reply to this email directly or view it on GitHub.     Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by mishin** [comment]
I move it to Free namespace https://metacpan.org/release/MISHIN/FamilyTreeInfo-2.3.26
Thanks for the comments
