### ISSUE TITLE
Can't convert from GEDCOM format to XLS

### ISSUE THREAD

**Issue by nigelhorne** [mishin/Ftree-cpan#3]
Hi,

I tried the program but I got this error:

$ perl mytree.ged ./tree.xls
Can't locate FamilyTreeDataFactory.pm in @INC (@INC contains: cgi cgi/lib /Users/njh/perl5/perlbrew/perls/perl-5.14.2/lib/site_perl/5.14.2/darwin-thread-multi-2level /Users/njh/perl5/perlbrew/perls/perl-5.14.2/lib/site_perl/5.14.2 /Users/njh/perl5/perlbrew/perls/perl-5.14.2/lib/5.14.2/darwin-thread-multi-2level /Users/njh/perl5/perlbrew/perls/perl-5.14.2/lib/5.14.2 .) at script/convertFormat.pl line 26.
BEGIN failed--compilation aborted at script/convertFormat.pl line 26.

**Comment by mishin** [comment]
Hi @nigelhorne , Thanks
for using it
convert usually work 
https://github.com/mishin/Ftree-cpan/tree/master/script
https://github.com/mishin/Ftree-cpan/blob/master/script/convert_to_ser.bat
"c:\Users\TOSH\Documents\job\perl\strawberry-perl-5.20.0.1-32bit-PDL\perl\bin\perl.exe" convertFormat.pl mishin_family.xls.xlsx mishin_family.xls.ser
I try to convert gedcom, may be it breaks

**Comment by mishin** [comment]
with error
but it works

[Sat Oct 31 16:01:10 2015] convertFormat.pl: Strange month: . Month should be be between 1 and 12 or the name of the month in english at C:/Users/TOSH/Documents/GitHub/dwimperl-windows/strawberry-perl-5.20.0.1-32bit-portable/perl/site/lib/DataParsers/FieldValidatorParser.pm line 84, <GEN0> line 1392.

c:\Users\TOSH\Documents\GitHub\Ftree-cpan\script>perl convertFormat.pl royal.ged royal.xls

**Comment by mishin** [comment]
it works
