### ISSUE TITLE
Instructions on README.md don't work

### ISSUE THREAD

**Issue by nigelhorne** [mishin/Ftree-cpan#4]
cpanm https://cpan.metacpan.org/authors/id/M/MI/MISHIN/FamilyTreeInfo-2.3.16.tar.gz

gives this:

--> Working on http://cpan.metacpan.org/authors/id/M/MI/MISHIN/FamilyTreeInfo-2.3.16.tar.gz
Fetching http://cpan.metacpan.org/authors/id/M/MI/MISHIN/FamilyTreeInfo-2.3.16.tar.gz ... OK
Configuring FamilyTreeInfo-2.3.16 ... OK
==> Found dependencies: Perl6::Export::Attrs
--> Working on Perl6::Export::Attrs
Fetching http://www.cpan.org/authors/id/D/DC/DCONWAY/Perl6-Export-Attrs-0.000004.tar.gz ... OK
Configuring Perl6-Export-Attrs-0.000004 ... OK
Building and testing Perl6-Export-Attrs-0.000004 ... FAIL
! Installing Perl6::Export::Attrs failed. See /Users/njh/.cpanm/work/1446433747.5514/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Perl6::Export::Attrs' is not installed
! Bailing out the installation for FamilyTreeInfo-2.3.16.

Which is not surprising Perl6::Export::Attrs is old and has lots of installation failures and appears to be unsupported.

http://matrix.cpantesters.org/?dist=Perl6-Export-Attrs+0.000004

**Comment by mishin** [comment]
Sorry it's old, you need only cpanm FamilyTreeInfo,I'll change it6:11, 2 ноября 2015 г., Nigel Horne notifications@github.com:cpanm https://cpan.metacpan.org/authors/id/M/MI/MISHIN/FamilyTreeInfo-2.3.16.tar.gz gives this: --> Working on http://cpan.metacpan.org/authors/id/M/MI/MISHIN/FamilyTreeInfo-2.3.16.tar.gz Fetching http://cpan.metacpan.org/authors/id/M/MI/MISHIN/FamilyTreeInfo-2.3.16.tar.gz ... OK Configuring FamilyTreeInfo-2.3.16 ... OK ==> Found dependencies: Perl6::Export::Attrs --> Working on Perl6::Export::Attrs Fetching http://www.cpan.org/authors/id/D/DC/DCONWAY/Perl6-Export-Attrs-0.000004.tar.gz ... OK Configuring Perl6-Export-Attrs-0.000004 ... OK Building and testing Perl6-Export-Attrs-0.000004 ... FAIL ! Installing Perl6::Export::Attrs failed. See /Users/njh/.cpanm/work/1446433747.5514/build.log for details. Retry with --force to force install it. ! Installing the dependencies failed: Module 'Perl6::Export::Attrs' is not installed ! Bailing out the installation for FamilyTreeInfo-2.3.16. Which is not surprising Perl6::Export::Attrs is old and has lots of installation failures and appears to be unsupported. http://matrix.cpantesters.org/?dist=Perl6-Export-Attrs+0.000004 —Reply to this email directly or view it on GitHub.     Sincerely, Nikolay Mishin

**Comment by mishin** [comment]
Thanks for the errors!

**Comment by mishin** [comment]
it works
